MODEL:
  NAME: dino
  PRETRAINED: None
  DIR: <path-to>/model_saved
  SAVE_NAME: dinov2_final_lr5e-4_sincos_pflash_ep100_adamw_clip3.0_reshape_layernorm_p12_channel3_gpu4_s42_wd.pt
  ROI: [96, 96, 96]
  IN_CHANS: 3
DATA:
  BASE_PATH: <path-to>/datasets
  TRAIN_CSV_PATH: <path-to>/datasets/train_final.csv
  VAL_CSV_PATH: <path-to>/datasets/val_final.csv
  TEST_CSV_PATH: <path-to>/datasets/test_final.csv
  NUM_WORKERS: 4
  CACHE_NUM: -1
  CACHE_RATE: 1.
  CACHE_DIR: <path-to>/dino_cache/
  NUM_CLASSES: 2
TRAIN:
  MAX_EPOCHS: 200
  VAL_EVERY: 10
  BASE_LR: 5e-4
  MIN_LR:  5e-8
  LOSS: L1
  PER_WARMUP: 0.1
  TEMPERATURE: 0.5
  BETA1: 0.9
  BETA2: 0.999
  WEIGHT_DECAY: 0.04
  WEIGHT_DECAY_END: 0.4
  GRAD_CLIP: 0.0
  OPTIMIZER: AdamW
  SCHEDULER: cosine
VIT:
  INPUT_SIZE: 96
  PATCH_SIZE: 12
  IN_CHANS: 3
  DROPOUT_RATE: 0.
  PATCH_EMBED: 'conv'
  POS_EMBED: 'sincos'
  NORM_LAYER: 'layernorm'
  SPATIAL_DIMS: 3
  HIDDEN_SIZE: 768
  NUM_LAYERS: 12
  MLP_DIM: 3072
  NUM_HEADS: 12
  NUM_REGISTER_TOKENS: 4
  PATCHES_OVERLAP: 0.2
  POOLING: 'cls'
  CLASSIFICATION: False
  USE_BIAS: True
DINO:
  GLOBAL_CROP_SIZE: [112, 112, 112]
  GLOBAL_CROP_NUM: 2
  LOCAL_CROP_SIZE: [64, 64, 64]
  LOCAL_CROP_NUM: 2
  HEAD_N_LAYERS: 3
  HEAD_N_PROTOTYPES: 65536
  BOTTLENECK_DIM: 256
  HEAD_HIDDEN_DIM: 2048
  MOMENTUM_TEACHER: 0.994
  MOMENTUM_TEACHER_END: 1.0
  WARMUP_TEACHER_TEMP: 0.04
  TEACHER_TEMP: 0.04
  WARMUP_TEACHER_EPOCHS: 30
  DINO_LOSS_WEIGHT: 1.0
  USE_BN: False
  NORM_LAST_LAYER: True
  FREEZE_LAST_LAYER: 1
WANDB:
  WANDB_ENABLE: False
  PROJECT: dino_final_lr5e-4_sincos_pflash_ep100_adamw_clip3.0_reshape_layernorm_p12_channel3_gpu4_s42_wd
LOG:
  FILENAME: dino_final_lr5e-4_sincos_pflash_ep100_adamw_clip3.0_reshape_layernorm_p12_channel3_gpu4_s42_wd
SEED: 42
OUTPUT: <path-to>/configs/dinov2/json
